
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 30 16:35:59 BRT 2015
//----------------------------------------------------

package xpr.version1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KEY_STRING = 36;
  public static final int RESTO = 13;
  public static final int OP_MAIOR_OU_IGUAL = 7;
  public static final int STRING_LITERAL = 28;
  public static final int KEY_CHAR = 35;
  public static final int MULT = 11;
  public static final int OP_MENOR_QUE = 6;
  public static final int CHAR_LITERAL = 27;
  public static final int SOMA = 9;
  public static final int ABRE_CHAVE = 20;
  public static final int FECHA_CHAVE = 21;
  public static final int DOIS_PONTOS = 24;
  public static final int VIRGULA = 22;
  public static final int KEY_DEF = 38;
  public static final int IDENTIFICADOR = 2;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int KEY_CALL = 37;
  public static final int ABRE_PAR = 18;
  public static final int OR = 15;
  public static final int KEY_WHILE = 31;
  public static final int KEY_FLOAT = 34;
  public static final int DIV = 12;
  public static final int FECHA_PAR = 19;
  public static final int OP_DIFERENTE = 4;
  public static final int EOF = 0;
  public static final int PONTO_VIRGULA = 23;
  public static final int error = 1;
  public static final int OP_MENOR_OU_IGUAL = 8;
  public static final int KEY_PRINT = 39;
  public static final int KEY_INT = 33;
  public static final int KEY_RETURN = 32;
  public static final int KEY_ELSE = 30;
  public static final int OP_IGUAL = 3;
  public static final int OP_MAIOR_QUE = 5;
  public static final int KEY_IF = 29;
  public static final int ATRIBUICAO = 17;
  public static final int FLOAT_LITERAL = 26;
  public static final int SUB = 10;
  public static final int INT_LITERAL = 25;
}

